apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: fiap/hackathon-video-image-converter
  namespace: fiap
  name: hackathon-video-image-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hackathon-video-image-converter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hackathon-video-image-converter
    spec:
      serviceAccountName: metrics-sa
      containers:
        - name: hackathon-video-image-converter
          image: 814482976567.dkr.ecr.us-east-1.amazonaws.com/hackathon-video-image-converter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4080
              protocol: TCP
          securityContext:
            runAsUser: 0  # Garantindo que rode como root
            runAsGroup: 0  # Garantindo que o grupo seja o root
            runAsNonRoot: false  # Permitindo execução como root
            allowPrivilegeEscalation: true  # Permite escalonamento de privilégios
          resources:
            requests:
              memory: "512Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "512m"
          envFrom:
            - secretRef:
                name: hackathon-video-image-secrets
            - configMapRef:
                name: hackathon-video-image-converter-vars
